name: New Blueprint
description: Submit a new Blueprint
title: '[Blueprint] '
labels: ['blueprint']
assignees: 'CollinHeist'

body:
  - type: input
    id: series_name
    attributes:
      label: Series Name
      description: What is the full name of the Series?
      placeholder: ex. The Wire
    validations:
      required: true

  - type: input
    id: series_year
    attributes:
      label: Series Year
      description: What year did this Series first air?
      placeholder: ex. 2002
    validations:
      required: true

  - type: input
    id: creator
    attributes:
      label: Creator Username
      description: Who would you like this Blueprint attributed to? If omitted, your GitHub username will be used.
      placeholder: ex. CollinHeist
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Blueprint Description
      description: A brief description of the Blueprint.
    validations:
      required: true
  
  - type: textarea
    id: blueprint
    attributes:
      label: Blueprint
      description: >
        Paste your `blueprint.json` file here.
        This will be automatically formatted as JSON, so there is no need for backticks.
      render: json
    validations:
      required: true

  - type: textarea
    id: preview_file
    attributes:
      label: Preview Title Card
      description: Upload your preview Title Card here.
    validations:
      required: true
      
  - type: textarea
    id: font_zip
    attributes:
      label: Zip of Font Files
      description: >
        Upload a `.zip` file of any Font Files used by this Blueprint. Please
        verify any Font Licenses allow them to be shared before uploading.
